apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-genie-server.fullname" . }}
  labels:
    {{- include "spring-genie-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: {{ .Values.service.adminPort }}
      protocol: TCP
      name: twitter-admin
  selector:
    {{- include "spring-genie-server.selectorLabels" . | nindent 4 }}
